### ISSUE TITLE
Some packages are deprecated and leaks memory

### ISSUE THREAD

**Issue by rameshnss** [vasu31dev/playwright-ts-template#29]
I observed few dependencies are deprecated and   One leaks memory. I could not find  which dependency is consuming these. I’m using windows OS.  I just cloned your lib and template project .  Please refer screenshot.
![IMG_0605](https://github.com/user-attachments/assets/3e52a8f9-2e0f-4466-be37-a0bdf150ecab)

**Comment by vasu31dev** [comment]
This issue is due to the ESLint packages. For now, it should not be a problem, and you can continue as is. Upgrading to the latest ESLint version and adjusting the rules and structure accordingly will resolve it. I can address this next quarter, but it should not cause any issues for now.

**Comment by rameshnss** [comment]
Ok thanks you so much for quick response
